title: Hello, world! I'm Joel Revington
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Joel Revington # add your name
position: Software Developer Lead #add your role
company: Pixel and Mortar
experience: Web Development | FrontEnd Development | Backend Development | Automation Testing
author-img: https://portfolio20072023.s3.ap-south-1.amazonaws.com/Joe.jpg # add your photo
about-author: I'm a passionate and dedicated software developer with a flair for building cutting-edge web applications. # add description
social-twitter: JoelRevington15 # add your Twitter handle
social-facebook: profile.php?id=100009270750468 # add your Facebook handle
social-github: JoelRevington1305 # add your Github handle
social-linkedin: joel-revington-105994135 # add your Linkedin handle
social-email: joelrevington28@gmail.com # add your Email address

# Disqus
discus-identifier: joel revington # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-sass-converter

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
